version: '3.8'

services:
    redis:
        image: redis
        ports: 
            - 6379:6379
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes: 
            - ./db_data:/var/lib/postgresql/data
        restart: always
    web:
        build: .
        ports:
          - "${PORT}:${PORT}"
        volumes:
          - ".:/app"
        restart: always
        depends_on:
          - db
        links:
          - "db:db"



            # ```
            # docker run --name redis-app -d redis
            # ```